# Generated by Django 4.2 on 2023-04-18 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "location_pref1",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Rotunda", "Rotunda"),
                            ("FD2 QT", "FD2 QT"),
                            ("NAB", "NAB"),
                        ],
                        default="Online",
                        max_length=100,
                    ),
                ),
                (
                    "location_pref2",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Rotunda", "Rotunda"),
                            ("FD2 QT", "FD2 QT"),
                            ("NAB", "NAB"),
                        ],
                        default="Online",
                        max_length=100,
                    ),
                ),
                (
                    "location_pref3",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Rotunda", "Rotunda"),
                            ("FD2 QT", "FD2 QT"),
                            ("NAB", "NAB"),
                        ],
                        default="Online",
                        max_length=100,
                    ),
                ),
                ("mics", models.IntegerField(default=0)),
                ("projector", models.BooleanField(default=False)),
                ("speakers", models.IntegerField(default=0)),
                (
                    "is_event_happening_for_the_first_time",
                    models.BooleanField(default=False),
                ),
                ("judgesheet", models.FileField(blank=True, upload_to="judgesheets/")),
                (
                    "registration_details",
                    models.TextField(default="No registration criteria as such"),
                ),
                ("PrizeMoney", models.IntegerField(default=0)),
                ("KindPoints", models.IntegerField(default=0)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
