# Generated by Django 4.2 on 2023-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_portal', '0005_event_remove_eventintro_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='final_location',
            field=models.CharField(choices=[('Online', 'Online'), ('Rotunda', 'Rotunda'), ('FD2 QT', 'FD2 QT'), ('NAB', 'NAB')], default='Online', max_length=100),
        ),
    ]
