# Generated by Django 4.2 on 2023-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
