# Generated by Django 4.2 on 2023-04-18 23:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_coordinator_delete_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinator",
            name="phone",
            field=phone_field.models.PhoneField(
                default="+91",
                help_text="Contact phone number",
                max_length=31,
                unique=True,
            ),
        ),
    ]
